### PR TITLE
- (IOS) Fix getProductInfo() and restoreTransaction()

### PR DESCRIPTION
**Pull request by tsangwailam**
- (IOS) Fix getProductInfo. event "PRODUCT_INFO_SUCCESS" change to "PRODUCT_INFO_RECEIVED"
- (IOS) Add native restoreTransaction() method. Use native [[SKPaymentQueue defaultQueue] restoreCompletedTransactions].

### CODE REVIEW

**Comment by florianbrochard** [comment]
@tsangwailam Hi, I've been testing your fixed ANE and I have an issue with restoreTransactions().
I've seen you had 2 new events. When I try to restore previous purchases in sandbox mod on iOS it doesn't seems to call any of the 3 RESTORE_ events.
In console I get [StatusEvent type="status" bubbles=false cancelable=false eventPhase=2 code="DEBUG" level="restoreCompletedTransactions"]
Do you have any idea?

**Comment by tsangwailam** [comment]
@florianbrochard 
It should fire RESTORE_COMPLETED_TRANSACTIONS if restore success. I test before it should work, will check later on.

**Comment by florianbrochard** [comment]
@tsangwailam Thanks it works!

**Comment by florianbrochard** [comment]
Hi @tsangwailam !
I've been testing the ANE for Android and discovered many issues.

First userCanMakeAPurchase doen't work on Android. Here the result in console :
[InAppPurchase]  in app purchase is supported 
[InAppPurchase] check user can make a purchase
ArgumentError: Error #3500: The extension context does not have a method with the name userCanMakeAPurchase.
    at flash.external::ExtensionContext/_call()
    at flash.external::ExtensionContext/call()
    at com.freshplanet.ane.AirInAppPurchase::InAppPurchase/userCanMakeAPurchase()[/Users/tsangwailam/Documents/Iphone Project/Digicrafts/library/ANE-In-App-Purchase-develop/actionscript/src/com/freshplanet/ane/AirInAppPurchase/InAppPurchase.as:130]
...

And more important, I can't make a purchase with the ANE. I never get a respond from the ANE, even an error
[InAppPurchase]  in app purchase is supported 
[InAppPurchase] purchasing android.test.purchased

First I though it was because of a miss-configuration for test users but it seems to came from the ANE.

**Comment by tsangwailam** [comment]
The android part is from original develop branch. I don't have chance to test it. I will work on android version later this week. May try to fix the problem.

**Comment by tsangwailam** [comment]
The original android ANE seem didn't implement the userCanMakePurcahse. I may try to implement it later on. 

I can make purchase with no problem. You may not setup your application descriptor xml property.

You need to add permission and activity in your application descriptor.

Permission

```
<uses-permission android:name="com.android.vending.BILLING" />
```

Activity

```
<activity android:name="com.freshplanet.inapppurchase.activities.BillingActivity" />
```

**Comment by florianbrochard** [comment]
Thanks. I did this but I never received any response from the ANE. Maybe I did something wrong. I'll try this later. Finally, I use this ANE https://github.com/pozirk/AndroidInAppPurchase from @pozirk for the Android part.

BTW, I found a new bug with the getProductsInfo method.

I received this when I ask for a product ID not existing on ItunesConnect (where "levels_pack_38" doesn't exist)

[InAppPurchase]  in app purchase is supported 
[InAppPurchase] get Products Info
[StatusEvent type="status" bubbles=false cancelable=false eventPhase=2 code="PRODUCT_INFO_RECEIVED" level="{}"]
[StatusEvent type="status" bubbles=false cancelable=false eventPhase=2 code="PRODUCT_INFO_ERROR" level="["levels_pack_38"]"]
[StatusEvent type="status" bubbles=false cancelable=false eventPhase=2 code="DEBUG" level="requestDidFinish"]

Only the PRODUCT_INFO_RECEIVED is catch by my app, whereas it shouldn't be dispatch at all if I'm not wrong.

**Comment by esdebon** [comment]
I reapply the fix made by @tsangwailam with a parameter in the restoreTransactions method.

With this you recover items purchased from the AppStore:
InAppPurchase.getInstance().restoreTransactions(true);

This fix was applied in the jhansen's version (this repo have many improves to android)

I test the ANE with iOS and Android with great results

https://github.com/Fluocode/ANE-In-App-Purchase

**Pull request closed without merging**
