### PR TITLE
Update Android BillingClient to v6.2.1

### PR DESCRIPTION
**Pull request by mtilhan**
According to Google Play documentation BillingClient v5 cant use anymore;

"By Aug 31, 2024, all new apps and updates to existing apps must use Billing Library version 6 or newer. If you need more time to update your app, you will be able to request an extension until Nov 1, 2024. https://developer.android.com/google/play/billing/deprecation-faq"

In this update, I upgraded the package to v6.2.1. Apparently, it can work without any changes other than the library update. But the difference is that v6 requires a lot of dependency. Since the current build also packages the necessary files, there was no problem, but those who use the same libraries may need to check.
https://mvnrepository.com/artifact/com.android.billingclient/billing/6.2.1

For the development to work, it is sufficient to make the following update in the manifest file.

`<meta-data android:name="com.google.android.play.billingclient.version" android:value="6.2.1" />`

### CODE REVIEW

**Comment by stephanberger4** [comment]
Hi. I've got an app that was made by a developer, and it uses "com.distriqt.InAppBilling.ane". I've received this message from Google Play that I need to use the last version of Google Play Billing Library version. 

Sorry for my incompetence but I'm having trouble finding the new version of this ANE on github so I can replace it with the current one I have. Would it be possible to send me a link where I can download this ANE please ? 

Sorry again 

Thx

**Comment by mtilhan** [comment]
Hi @stephanberger4,

My code hasn't been merged yet. If you want to use the version I made, you can download it from here: https://github.com/mtilhan/ANE-In-App-Purchase/tree/feature/update-billing-v6/bin.

However, if you are using the "com.distriqt.InAppBilling.ane" extension you mentioned, unfortunately it will not be enough to just change it, you will also have to rewrite the code it uses with this extension.

I hope the Freshplanet team can also find time to review the PR for users using this extension. 
@mateo-kozomara @dmytrooverchenko 

Regards.

**Review by dmytrooverchenko — COMMENTED** [review]
Hello @mtilhan,
Thank you a lot for your contribution. Could you please make this PR independent from this https://github.com/freshplanet/ANE-In-App-Purchase/pull/113 with changes only for Android BillingClient version upgrade?

**Comment by mtilhan** [comment]
Hello @dmytrooverchenko, sorry for that. Should I revert the other commit or would it be cleaner if I close this PR and open a new one?

**Review by dmytrooverchenko — APPROVED** [review]
Since there will be only necessary changes after merge I'll merge it like this. Good job.

**Pull request merged**
